# Go-NetGate 配置文件

server:
  # 监听地址和端口
  port: "8443"
  tls_mode: "tls" # 可选值：tls、gmtls

# 负载均衡配置
load_balance:
  # 后端服务器列表
  backends:
    - "http://localhost:9001"
    - "http://localhost:9002"
    - "http://localhost:9003"
  # 负载均衡算法（基础轮询-RR、IP哈希-IPHash）
  algorithm: "RR"

# 国密证书配置
gmtls:
  SignCertFile: "./certs/SS.crt"
  SignKeyFile: "./certs/SS.key"
  EncCertFile: "./certs/SE.crt"
  EncKeyFile: "./certs/SE.key"
    
# 标准tls证书配置
tls:
  cert_file: "./certs/standard.crt"
  key_file: "./certs/standard.key"

# Redis 配置
redis:
  addr: "localhost:6380"
  password: ""
  db: 0
  pool_size: 100

# 分布式限流配置
redis_rate_limit:
  rate: 5   # 每秒生成的令牌数
  burst: 10 # 令牌桶容量

# 单机限流配置
single_rate_limit:
  rate: 5   # 每秒生成的令牌数
  burst: 10 # 令牌桶容量


